version: "3"
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"